# ================================================================
# File: .sops.yaml
# Purpose:
#   SOPS creation rules for secrets stored under state/secrets/
# ================================================================
creation_rules:
  - path_regex: ^state/secrets/.*\.(ya?ml|json|env|ini|txt|conf)$
    age: >-
      age1tcmauv82tx9he2542um4egrn2efzjrqt4cmqn63fschl7zx8recsuj9nr7,age1vzw0jjt46ekdykykj7xl98gw3pj4vf5evljmpegtz4dy0jq7qcmqgvvw23
