# ##################################################################################################
# File: .sops.yaml
# Purpose:
#   SOPS encryption rules for fouchger-homelab.
# Notes:
#   - Recipient is derived from state/secrets/age/age-key.txt (single source of truth).
# ##################################################################################################

creation_rules:
  - path_regex: ^state/secrets/sops/.*\.(ya?ml|json|env|ini)$
    encrypted_regex: '^(data|stringData|secrets|secret|token|password|key|keys|private|config)$'
    age: ["age1ztf9lmuqpkdmk6d248wz3mqknmdwra2rsmlsphyv2r7cc8sn05hsp0nah4"]

  - path_regex: ^ansible/group_vars/.*/.*(secret|secrets)\.(ya?ml|json)$
    age: ["age1ztf9lmuqpkdmk6d248wz3mqknmdwra2rsmlsphyv2r7cc8sn05hsp0nah4"]

  - path_regex: ^state/secrets/openbao/.*(\.enc)?\.(ya?ml|json)$
    age: ["age1ztf9lmuqpkdmk6d248wz3mqknmdwra2rsmlsphyv2r7cc8sn05hsp0nah4"]
