# ================================================================
# File: .sops.yaml
# Purpose:
#   SOPS creation rules for secrets stored under state/secrets/
# ================================================================
creation_rules:
  - path_regex: ^state/secrets/.*\.(ya?ml|json|env|ini|txt|conf)$
    age: >-
      age1upe6qk6dyx2u5fsuanzjn9dlcaug0qnu90mepqpz7l9g38z7vc5qpvad7e,age1tr7jagz98pp6x9qu8m7434chkr0yq4akfqfdnjax4umlf6gw7vtqaqu9ug
