# ###########################################################################
# File: Taskfile.yml
# Description:
#   Bootstrap Taskfile for fouchger-homelab hosts.
#   Each item can be run independently or combined via the `bootstrap` task.
#
# Notes:
#   - Designed for Debian/Ubuntu (and Proxmox host shells where apt is available).
#   - Most tasks require sudo/root for apt installs.
#   - Ansible is installed via pipx (isolated Python tooling).
#   - Terraform and Packer default to HashiCorp apt repository installs.
#   - Code Server uses the community Proxmox script you specified (network required).
#
# Usage:
#   task -l
#   task bootstrap
#   task upgrade
#   task ansible
#   task terraform
#   task packer
#   task code-server
# ###########################################################################

version: "3"

vars:
  APT_GET: "apt-get"
  SUDO: "{{.SUDO | default \"sudo\"}}"
  DEBIAN_FRONTEND: "noninteractive"
  HASHICORP_KEYRING: "/usr/share/keyrings/hashicorp-archive-keyring.gpg"
  HASHICORP_LIST: "/etc/apt/sources.list.d/hashicorp.list"

env:
  DEBIAN_FRONTEND: "{{.DEBIAN_FRONTEND}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task -l

  bootstrap:
    desc: Run full bootstrap (upgrade system + install all requested tools)
    deps:
      - upgrade
      - python3
      - pipx
      - ansible
      - terraform
      - packer
      - code-server

  upgrade:
    desc: Upgrade the system (update, full-upgrade, autoremove)
    cmds:
      - "{{.SUDO}} {{.APT_GET}} update -y"
      - "{{.SUDO}} {{.APT_GET}} full-upgrade -y"
      - "{{.SUDO}} {{.APT_GET}} autoremove -y"
      - "{{.SUDO}} {{.APT_GET}} autoclean -y"

  python3:
    desc: Install Python3 tooling required for pipx
    cmds:
      - "{{.SUDO}} {{.APT_GET}} update -y"
      - >
        {{.SUDO}} {{.APT_GET}} install -y
        python3 python3-venv python3-pip
    status:
      - command -v python3 >/dev/null 2>&1

  pipx:
    desc: Install pipx and ensure PATH is configured for the current user
    deps:
      - python3
    cmds:
      - "{{.SUDO}} {{.APT_GET}} update -y"
      - "{{.SUDO}} {{.APT_GET}} install -y pipx"
      - "pipx ensurepath || true"
      - "python3 -m pipx ensurepath || true"
    status:
      - command -v pipx >/dev/null 2>&1

  ansible:
    desc: Install Ansible via pipx (isolated install)
    deps:
      - pipx
    cmds:
      - "pipx install --include-deps ansible || pipx upgrade ansible"
      - "ansible --version"
    status:
      - command -v ansible >/dev/null 2>&1

  hashicorp-repo:
    desc: Add HashiCorp apt repository (Terraform/Packer)
    cmds:
      - "{{.SUDO}} {{.APT_GET}} update -y"
      - "{{.SUDO}} {{.APT_GET}} install -y ca-certificates curl gnupg lsb-release"
      - "{{.SUDO}} install -m 0755 -d /etc/apt/keyrings"
      - >
        curl -fsSL https://apt.releases.hashicorp.com/gpg |
        {{.SUDO}} gpg --dearmor -o {{.HASHICORP_KEYRING}}
      - "{{.SUDO}} chmod a+r {{.HASHICORP_KEYRING}}"
      - >
        echo "deb [signed-by={{.HASHICORP_KEYRING}}] https://apt.releases.hashicorp.com $(lsb_release -cs) main" |
        {{.SUDO}} tee {{.HASHICORP_LIST}} >/dev/null
      - "{{.SUDO}} {{.APT_GET}} update -y"
    status:
      - test -f "{{.HASHICORP_LIST}}"

  terraform:
    desc: Install Terraform (HashiCorp apt repo)
    deps:
      - hashicorp-repo
    cmds:
      - "{{.SUDO}} {{.APT_GET}} install -y terraform"
      - "terraform version"
    status:
      - command -v terraform >/dev/null 2>&1

  packer:
    desc: Install Packer (HashiCorp apt repo)
    deps:
      - hashicorp-repo
    cmds:
      - "{{.SUDO}} {{.APT_GET}} install -y packer"
      - "packer version"
    status:
      - command -v packer >/dev/null 2>&1

  code-server:
    desc: Install code-server (defaults to standard installer; optional Proxmox script via USE_PROXMOX_SCRIPT=1)
    cmds:
      - |
        set -euo pipefail

        # If already installed, do nothing.
        if command -v code-server >/dev/null 2>&1; then
          echo "code-server already installed. Skipping."
          exit 0
        fi

        use_proxmox_script="${USE_PROXMOX_SCRIPT:-0}"

        if [ "$use_proxmox_script" = "1" ]; then
          # Guardrails: only allow Proxmox script when running in a VM or container.
          if command -v systemd-detect-virt >/dev/null 2>&1; then
            virt="$(systemd-detect-virt || true)"
            cont="$(systemd-detect-virt -c || true)"

            if [ "$virt" = "none" ] && [ "$cont" = "none" ]; then
              echo "USE_PROXMOX_SCRIPT=1 set, but no virtualisation detected (bare metal). Refusing to run Proxmox script."
              echo "Unset USE_PROXMOX_SCRIPT or run standard installer."
              exit 1
            fi
          else
            echo "USE_PROXMOX_SCRIPT=1 set, but systemd-detect-virt is unavailable. Refusing to run Proxmox script."
            echo "Unset USE_PROXMOX_SCRIPT or install systemd tooling."
            exit 1
          fi

          echo "USE_PROXMOX_SCRIPT=1 set. Installing via Proxmox community script."
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/addon/coder-code-server.sh)"
          exit 0
        fi

        echo "Installing via standard code-server installer."
        curl -fsSL https://code-server.dev/install.sh | sh
    status:
      - command -v code-server >/dev/null 2>&1
