# ###########################################################################
# File: Taskfile.yml
# Description:
#   `bootstrap` task.
#
# Notes:
#   - 
#
# Usage:
#   
# ###########################################################################

version: "3"

includes:
  bootstrap: ./tasks/bootstrap.Taskfile.yml
  git_gh: ./tasks/git_gh.Taskfile.yml
  ansible: ./tasks/ansible.Taskfile.yml
  secrets: ./tasks/secrets.Taskfile.yml
  # platform: ./tasks/platform.Taskfile.yml
  # tooling: ./tasks/tooling.Taskfile.yml
  # services: ./tasks/services.Taskfile.yml
  # maintenance: ./tasks/maintenance.Taskfile.yml
  lib: ./tasks/lib/checks.Taskfile.yml

tasks:
  default:
    desc: List tasks
    cmds:
      - task -l

  bootstrap:
    desc: Full bootstrap of a host
    cmds:
      - task: bootstrap:all

  secrets:once:
    desc: "Once-off secrets setup only (SOPS+age, SSH keys, OpenBao baseline)."
    cmds:
      - task: secrets:secrets
    silent: false