# ###########################################################################
# File: Taskfile.yml
# Description:
#   `bootstrap` task.
#
# Notes:
#   - 
#
# Usage:
#   
# ###########################################################################

version: "3"

includes:
  bootstrap: ./tasks/bootstrap.Taskfile.yml
  scm: ./tasks/authenticate.Taskfile.yml
  # platform: ./tasks/platform.Taskfile.yml
  # tooling: ./tasks/tooling.Taskfile.yml
  # services: ./tasks/services.Taskfile.yml
  # maintenance: ./tasks/maintenance.Taskfile.yml
  lib: ./tasks/lib/checks.Taskfile.yml

tasks:
  default:
    desc: List tasks
    cmds:
      - task -l

  bootstrap:
    desc: Full bootstrap of a host
    cmds:
      - task: bootstrap:all