# ###########################################################################
# File: Taskfile.yml
# Description:
#   `bootstrap` task.
#
# Notes:
#   - 
#
# Usage:
#   
# ###########################################################################

version: "3"

includes:
  bootstrap: ./tasks/bootstrap.Taskfile.yml
  git_gh: ./tasks/git_gh.Taskfile.yml
  ansible: ./tasks/ansible.Taskfile.yml
  secrets: ./tasks/secrets.Taskfile.yml
  # platform: ./tasks/platform.Taskfile.yml
  # tooling: ./tasks/tooling.Taskfile.yml
  # services: ./tasks/services.Taskfile.yml
  # maintenance: ./tasks/maintenance.Taskfile.yml
  lib: ./tasks/lib/checks.Taskfile.yml

tasks:
  default:
    desc: List tasks
    cmds:
      - task -l

  run:
    desc: Single entry-point to execute a standard host setup (bootstrap + optional once-off secrets)
    cmds:
      - |
        set -euo pipefail
        echo "This will run: secrets:once (optional) then bootstrap." 
        if [ "${RUN_SECRETS_ONCE:-0}" = "1" ]; then
          task secrets:once
        else
          echo "Skipping secrets:once (set RUN_SECRETS_ONCE=1 to enable)."
        fi
        task bootstrap

  bootstrap:
    desc: Full bootstrap of a host
    cmds:
      - task: bootstrap:all

  secrets:once:
    desc: "Once-off secrets setup only (SOPS+age, SSH keys, OpenBao baseline)."
    cmds:
      - task: secrets:secrets
    silent: false

  git_gh:
    desc: "Once-off authorising Git & GitHub"
    cmds:
      # Install first so auth does not fail on fresh hosts.
      - task: git_gh:bootstrap
    silent: false

