# Taskfile.yml
# Project: fouchger-homelab
# Purpose: Bootstrap a host with Git + gh, then clone/update the repo into dev or prod.
# Notes:
# - Requires go-task to run this file. Use bootstrap.sh on a fresh host.

version: "3"

silent: false

vars:
  ENV: '{{default "dev" .ENV}}'

  # Requested defaults
  REPO: '{{default "Fouchger/Fouchger_Homelab" .REPO}}'
  BRANCH: '{{default "main" .BRANCH}}'

  # Destination roots
  DEV_DIR: '{{default (printf "%s/Github/Fouchger_Homelab" .HOME) .DEV_DIR}}'
  PROD_DIR: '{{default "/opt/prod" .PROD_DIR}}'

  REPO_NAME:
    sh: |
      set -e
      r="{{.REPO}}"
      r="${r%.git}"
      echo "$(basename "$r")"

  DEST_DIR:
    sh: |
      set -e
      if [ "{{.ENV}}" = "prod" ]; then
        echo "{{.PROD_DIR}}/{{.REPO_NAME}}"
      else
        # Dev should be the repo folder itself (no nesting)
        echo "{{.DEV_DIR}}"
      fi

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  doctor:
    desc: Validate environment and show resolved paths
    cmds:
      - |
        set -e
        echo "ENV={{.ENV}}"
        echo "REPO={{.REPO}}"
        echo "BRANCH={{.BRANCH}}"
        echo "DEST_DIR={{.DEST_DIR}}"
        command -v git >/dev/null 2>&1 && echo "git: OK" || echo "git: MISSING"
        command -v gh  >/dev/null 2>&1 && echo "gh:  OK" || echo "gh:  MISSING"
        command -v task >/dev/null 2>&1 && echo "task: OK" || echo "task: MISSING (run bootstrap.sh)"

  bootstrap:
    desc: Install Git + gh, then clone/update the repo into ENV=dev|prod
    cmds:
      - install:prereqs
      - install:git
      - install:gh
      - repo:sync

  install:prereqs:
    desc: Install base prerequisites used by other tasks
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y ca-certificates curl gnupg lsb-release

  install:git:
    desc: Install Git
    status:
      - command -v git >/dev/null 2>&1
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y git
      - git --version

  install:gh:
    desc: Install GitHub CLI (gh)
    status:
      - command -v gh >/dev/null 2>&1
    cmds:
      - sudo mkdir -p /etc/apt/keyrings
      - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null
      - sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
      - >
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg]
        https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
      - sudo apt-get update
      - sudo apt-get install -y gh
      - gh --version

  gh:auth:
    desc: Authenticate gh (interactive, needed for private repos)
    cmds:
      - gh auth status || true
      - gh auth login

  repo:sync:
    desc: Clone or update the repo (checks out BRANCH)
    preconditions:
      - sh: |
          if [ "{{.ENV}}" = "dev" ] || [ "{{.ENV}}" = "prod" ]; then exit 0; fi
          exit 1
        msg: "ENV must be dev or prod."
    cmds:
      - |
        set -e
        echo "Destination: {{.DEST_DIR}}"

        if [ "{{.ENV}}" = "prod" ]; then
          sudo mkdir -p "{{.PROD_DIR}}"
          sudo chown -R "$(id -u):$(id -g)" "{{.PROD_DIR}}"
        else
          mkdir -p "$(dirname "{{.DEV_DIR}}")"
        fi

        if [ -d "{{.DEST_DIR}}/.git" ]; then
          echo "Repo exists, updating..."
          cd "{{.DEST_DIR}}"
          git fetch --all --prune
          git checkout "{{.BRANCH}}"
          git pull
          exit 0
        fi

        echo "Cloning {{.REPO}}..."
        if echo "{{.REPO}}" | grep -qE '^https?://|^git@'; then
          git clone --branch "{{.BRANCH}}" "{{.REPO}}" "{{.DEST_DIR}}"
        else
          gh repo clone "{{.REPO}}" "{{.DEST_DIR}}" -- --branch "{{.BRANCH}}"
        fi

  repo:status:
    desc: Show git status
    preconditions:
      - sh: '[ -d "{{.DEST_DIR}}/.git" ]'
        msg: "Repo not found at {{.DEST_DIR}}. Run task repo:sync first."
    cmds:
      - cd "{{.DEST_DIR}}" && git status
